<?php
/**
 * PacNet's Raven Payment Gateway
 *
 * MIT License
 *
 * Copyright (c) 2016, PacNet Services Ltd
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * @category    PacNet
 * @package     PacNet_Raven
 * @author      Joerg Beekmann <joerg@deepcovelabs.com>
 * @link        https://pacnetservices.com/
 * @copyright   Copyright (c) 2016, PacNet Services Ltd
 * @license     https://opensource.org/licenses/MIT MIT License
 */

/**
 * Template displays the Raven MarkDirect form and redirect
 * @see PacNet_Raven_MarketdirectController::redirectAction()
 */
?>
<div align="center">
	<h1><?php echo Mage::helper('pacnet_raven')->__('Payment with') . ' ' . $this->raven_transaction->getPaymentTitle() ?></h1>
	<p><img src='<?php echo $this->getSkinUrl('pacnet/images/ajax-loader.gif') ?>' /></p>
	<p><?php echo Mage::helper('pacnet_raven')->__('Proceeding to payment...') ?></p>
	<p><small><?php echo Mage::helper('pacnet_raven')->__('You are now entering a secure payment portal with Raven MarketDirect. If you are not automatically redirected within 5 seconds please...') ?></small></p>
	<br />
	<form action="<?php echo PacNet_Raven_Model_MarketDirect_Transaction::RAVEN_PAYMENT_URI ?>"
	  method="post" name="raven_marketdirect_form" id="raven_marketdirect_form">
		<?php echo $this->form_data ?>
		<p><input type="submit" name="submit" id="raven_marketdirect_form_submit" class="button" value="<?php echo Mage::helper('pacnet_raven')->__('Click here to Pay Now') ?>" /></p>
	</form>
</div>
<script>
	jQuery(function () {
		jQuery('#raven_marketdirect_form_submit').click();
	});
</script>